execute @s ~ ~ ~ detect ~ ~ ~ l0 -1 scoreboard players set @s input_buf 0
execute @s ~ ~ ~ detect ~ ~ ~ l1 -1 scoreboard players set @s input_buf 1
execute @s ~ ~ ~ detect ~ ~ ~ l2 -1 scoreboard players set @s input_buf 2
execute @s ~ ~ ~ detect ~ ~ ~ l3 -1 scoreboard players set @s input_buf 3
execute @s ~ ~ ~ detect ~ ~ ~ l4 -1 scoreboard players set @s input_buf 4
execute @s ~ ~ ~ detect ~ ~ ~ l5 -1 scoreboard players set @s input_buf 5
execute @s ~ ~ ~ detect ~ ~ ~ l6 -1 scoreboard players set @s input_buf 6
execute @s ~ ~ ~ detect ~ ~ ~ l7 -1 scoreboard players set @s input_buf 7
execute @s ~ ~ ~ detect ~ ~ ~ l8 -1 scoreboard players set @s input_buf 8
execute @s ~ ~ ~ detect ~ ~ ~ l9 -1 scoreboard players set @s input_buf 9
execute @s ~ ~ ~ detect ~ ~ ~ air -1 scoreboard players set @s input_buf -1